os: linux
dist: bionic
language: node_js
node_js:
  - "12"
before_script: npx firebase use slides-today
cache:
  directories:
    - dist
jobs:
  include:
    - stage: Build
      name: Production
      script: npm run build:prod
    - name: Development
      cache: false
      script:
        - npm run build
        - npm run build:scripts
    - name: Lint
      cache: false
      script: npm run lint
    - name: Security
      cache: false
      script: npm audit
    - stage: Test
      name: Features
      script: npm run test:features
    - name: Lighthouse
      script: npm run lighthouse
    - name: Bundlesize
      script: npm run bundlesize
    - stage: Deploy
      name: Firebase
      if: branch = master
      script: true
      deploy:
        provider: firebase
        edge: true
  allow_failures:
    - script: npm audit
