os: linux
dist: bionic
language: node_js
node_js:
  - "12"
jobs:
  include:
    - name: Lint
      script: npm run lint
    - name: Build
      script:
        - npm run build:scripts
        - npm run build
    - name: Build Prod
      script:
        - npm run build:prod
        - npm run bundlesize
    - name: Feature Tests
      script: npm test
    - name: Lighthouse
      script:
        - npm run build:prod
        - npm run lighthouse
    - name: Security
      script: npm audit
  allow_failures:
    - script: npm audit
