language: node_js
node_js:
  - "12"
before_install:
  - npm i -D typescript # Remove when @justinribeiro/lite-youtube switches back to NPM
jobs:
  include:
    - name: Lint
      script: npm run lint
    - name: Build
      script: npm run build
    - name: Build Scripts
      script: npm run build:scripts
    - name: Build Prod
      script:
        - npm run build:prod
        - npm run bundlesize
