import { Deck } from './deck';
import { Link } from './link';

export const DECKS: Deck[] = [
  {
    id: '-KuK3ne8fybZfk46Awp',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego bricks of the web',
    date: 'September 21st, 2017',
    description: 'Writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Use the native web platform to build performant, lightweight building blocks for your site. We will show you how to build custom elements using best practices and how to integrate them with your project.',
    eventTitle: 'Connect.Tech',
    tags: ['webcomponents'],
    location: 'Atlanta, GA',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/15Kx0hYzH9V50qvbqSpFJTgX0lhejC6QK5UlkcVgvX0I',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'http://connect.tech/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KuK2kY4Q3-cRwoh5wA5',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Energize your development flow with CLIs',
    date: 'September 21st, 2017',
    description: 'Creating personalized CLIs can help you streamline recurring tasks, such as setting up new development environments, managing deployments, and wrangling data. We will walk you through building CLIs in JavaScript to help you avoid costly mistakes and ensure consistent results. Create simple commands that perform powerful tasks.',
    eventTitle: 'Connect.Tech',
    tags: ['cli', 'javascript'],
    location: 'Atlanta, GA',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1CMsM3JGjldazx0efpaLjJVoKsXg8NQYmiKoPwIa6SKo',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'http://connect.tech/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KuK2OlDHUH8HD4-Qp2W',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Material Design that Delights',
    date: 'September 21st, 2017',
    description: 'By reputation, programmers aren’t great designers. “Designed by developers” usually implies a terrible user experience. Material Design is helping to change this. Google’s UX designers have developed and refined the principles behind Material Design through testing with billions of users. Using Material Design, you can create intuitive experiences with smooth animations that delight users and showcase your brand. We’ll explain Material Design principles and show you how to implement them.',
    eventTitle: 'Connect.Tech',
    tags: ['materialdesign'],
    location: 'Atlanta, GA',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1-34iJL28_Mxa39KJUeMRY5Ozb5mT8e5ovQbSLzw4s_0',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'http://connect.tech/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KsEs5JMWk87ZisLpW1F',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Material Design that Delights',
    date: 'September 16th, 2017',
    description: 'By reputation, programmers aren’t great designers. “Designed by developers” usually implies a terrible user experience. Material Design is helping to change this. Google’s UX designers have developed and refined the principles behind Material Design through testing with billions of users. Using Material Design, you can create intuitive experiences with smooth animations that delight users and showcase your brand. We’ll explain Material Design principles and show you how to implement them.',
    eventTitle: 'GDG Madison',
    tags: ['materialdesign'],
    location: 'Madison, WI',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1_6parH6T8iUSZgjoVSI8nCYyYNL1rKyLAUoRrfxRsdk',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.meetup.com/gdg-madison/events/242690232/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KsK81gOZiIkIWcL5AhZ',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp'],
    title: 'Making Slides.today',
    date: 'August 24th, 2017',
    description: 'Slides.today was created to provide a better experience for session attendees. Get an overview of the problems being solved, the tech stack making it all possible and the bumpy spots along the way.',
    eventTitle: 'GDE Web Technologies Hangout',
    tags: ['angular', 'progressivewebapps', '⚡'],
    location: 'Earth',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/12FIksFEGPhPXVdNdvElFXD-wb5iRYqV7BXAQ3zlxjco',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Demo',
        url: 'https://slides.today',
        tag: true,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-Krv_65pE2p9nJUXkhFl',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Leverage the power of native with Progressive Web Apps',
    date: 'August 22nd, 2017',
    description: 'As developers, we want to create apps that engage users across multiple devices. But building native apps is costly and cumbersome. Progressive Web Apps (PWAs) combine the power of native apps with the ease of building and deploying web apps. Learn to craft PWA experiences using new web standards, including service workers, push notifications, and homescreen access.',
    eventTitle: 'Midwest JS',
    tags: ['progressivewebapps'],
    location: 'Minneapolis, MN',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1TybgcgjmAFB8AHTOQzBMrKOc4XAma-HFEvdWqdXUOQc',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'http://www.midwestjs.com/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-Krv_4SqDbjoADBL6r3Q',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego Bricks of the Web',
    date: 'August 17th, 2017',
    description: 'Writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Ditch large, complex frameworks and drop these lightweight building blocks into your site. We will show you how to build custom elements and introduce you to the existing elements and tools available from Google’s Polymer Project.',
    eventTitle: 'Midwest JS',
    tags: ['webcomponents', 'polymer'],
    location: 'Minneapolis, MN',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1TXePoX459CGL8EEPYiAoLLdF092ev4f-GW0FK8Ftn6o',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'http://www.midwestjs.com/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-Krv_2GgLtDjYwGOEm8v',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego Bricks of the Web',
    date: 'August 8th, 2017',
    description: 'Are you writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Ditch large, complex frameworks and drop these lightweight building blocks into your site. We will show you how to build custom elements and introduce you to the existing elements and tools available from Google’s Polymer Project.',
    eventTitle: 'Rockford Web Devs',
    tags: ['webcomponents', 'polymer'],
    location: 'Rockford, IL',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1wgFQACcTgft_lVSgFsduMLznG-iCM4NFF4bC6ZNYR6M',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.meetup.com/Rockford-Web-Devs/events/238442439/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-Krv_0Yp5bPmylxcTnss',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego Bricks of the Web',
    date: 'August 3rd, 2017',
    description: 'Are you writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Ditch large, complex frameworks and drop these lightweight building blocks into your site. We will show you how to build custom elements and introduce you to the existing elements and tools available from Google’s Polymer Project.',
    eventTitle: 'KCDC',
    tags: ['webcomponents', 'polymer'],
    location: 'Kansas City, MO',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1k9uS824i0sieSy0O9KSBN67quT_5ZXQbC-w0P06PrWk',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'http://www.kcdc.info/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZzUSqxYoXmJWLGun',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Get the Power of Native with Progressive Web Apps',
    date: 'July 22nd, 2017',
    description: 'As developers, we want to create apps that engage users across multiple devices. But building native apps is costly and cumbersome. Progressive Web Apps (PWAs) combine the power of native apps with the ease of building and deploying web apps. Learn to craft PWA experiences using new web standards, including service workers, push notifications, and home screen access.',
    eventTitle: 'CoderCruise',
    tags: ['progressivewebapps'],
    location: 'Cozumel, Mexico',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1CGLXYGKqyb5Jxt62DAGDN8gjNJ56vZNJCzIG2OT6d64',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.codercruise.com/',
        tag: false,
        service: 'external',
      },
      {
        title: 'Reviews',
        url: 'https://joind.in/event/codercruise/get-the-power-of-native-with-progressive-web-apps',
        tag: true,
        service: 'joindin',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZxXjRvdxuo_pWZGy',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Getting Started with the Twitter API',
    date: 'July 18th, 2017',
    description: 'Learn from the author of TwitterOAuth how to quickly integrate your application with the Twitter API. We will show you how to speed up onboarding with “Sign in with Twitter” authentication, bootstrap profiles with Twitter identities, and increase reach with quick publishing to user timelines. We’ll go over some basic do’s and don’ts of the Twitter API and show how easy it is to integrate using the TwitterOAuth open source library.',
    eventTitle: 'CoderCruise',
    tags: ['twitterapi', 'php'],
    location: 'Grand Cayman, Cayman Islands',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1TCVGVUZ0BFNAcf56mxyMQI7hHUOp2GzRwOKkZJ_lQi0',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.codercruise.com/',
        tag: false,
        service: 'external',
      },
      {
        title: 'Reviews',
        url: 'https://joind.in/event/codercruise/getting-started-with-the-twitter-api',
        tag: true,
        service: 'joindin',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZtwL_ZafufriB-ta',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego Bricks of the Web',
    date: 'July 17th, 2017',
    description: 'Are you writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Ditch large, complex frameworks and drop these lightweight building blocks into your site. We will show you how to build custom elements and introduce you to the existing elements and tools available from Google’s Polymer Project.',
    eventTitle: 'CoderCruise',
    tags: ['webcomponents', 'polymer'],
    location: 'Montego Bay, Jamaica',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1ddQ12a2EtnVRgWl4fCqK3HCfB3JvXlJrPm2oqS_HwbI',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.codercruise.com/',
        tag: false,
        service: 'external',
      },
      {
        title: 'Reviews',
        url: 'https://joind.in/event/codercruise/web-components-lego-bricks-of-the-web',
        tag: true,
        service: 'joindin',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZsDivrXv69eEkiRs',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Leverage the power of native with Progressive Web Apps',
    date: 'July 10th, 2017',
    description: 'As developers, we want to create apps that engage users across multiple devices. But building native apps is costly and cumbersome. Progressive Web Apps (PWAs) combine the power of native apps with the ease of building and deploying web apps. Learn to craft PWA experiences using new web standards, including service workers, push notifications, and homescreen access.  ',
    eventTitle: 'MadJS',
    tags: ['progressivewebapps'],
    location: 'Madison, WI',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/14FhXTP0Kx0Uli5YTzQcIWVUqKI7_-U_vr8NSZEo0rJA',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.meetup.com/MadisonJS/events/238952227/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZof6--agoRIC6vl0',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Google I/O Recap',
    date: 'June 15th, 2017',
    description: 'Experience highlights from the May 2017 Google I/O developer festival. Every spring, Google invites thousands of developers to a three-day festival where Google engineers and product managers teach technical skills, share insights, and announce new developer products. Abraham and Pearl will be there and they’re excited to tell you what they learned. ',
    eventTitle: 'GDG Madison',
    tags: ['googleio'],
    location: 'Madison, WI',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1J2VBd_msTRcZGuNk_Pj2i4SZEVXM_-hbsFW_kXxa_KE',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.meetup.com/gdg-madison/events/239355851/',
        tag: false,
        service: 'meetup',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-Kt8ZOHSO3M-nLnxH8Fh',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'How to be a professional developer',
    date: 'April 27th, 2017',
    description: 'We will share our stories becoming professional software developers. Where the adentures took us. What went wrong along the way. And what to consider when you start your journey.',
    eventTitle: 'UW Madison CS Lecture',
    tags: ['culture'],
    location: 'Madison, WI',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1VFobwLLehLUePGT5EyGkzAqRJVC-UPmxtFEgVqlKFh0',
        tag: false,
        service: 'google-slides',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZmqmksA5WVIr1uoA',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Get talking with Actions on Google',
    date: 'April 15th, 2017',
    description: 'Let your users be the voice talent with Actions on Google. Learn how to design, develop, and distribute rich conversational experiences or direct action commands. We’ll show you how to approach voice-driven, natural language interactions with API.AI’s powerful bot platform.',
    eventTitle: 'GDG Madison',
    tags: ['actionsongoogle'],
    location: 'Madison, WI',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1trLvZmpDJca7Z0c-DaSUZg2ChdqFN5vj04q--TCcQKI',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.meetup.com/gdg-madison/events/237914183/',
        tag: false,
        service: 'meetup',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZlA6DeLeyBqBT4Jy',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego bricks of the web',
    date: 'March 22nd, 2017',
    description: 'Writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Use the native web platform to build performant, lightweight building blocks for your site. We will show you how to build custom elements using best practices and how to integrate them with your Angular project.',
    eventTitle: 'JazzCon.Tech',
    tags: ['webcomponents', 'angular'],
    location: 'New Orleans, LA',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/13ISIYU6v7xVY0IKMTBIi8VHI-VsIjwqBspAEbxspCCU',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'http://jazzcon.tech/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZjBO9DYgRe8s1IvT',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego bricks of the web',
    date: 'Februery 18th, 2017',
    description: 'Writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Ditch large, complex frameworks and drop these lightweight building blocks into your site. We will show you how to build custom elements and introduce you to the existing elements and tools available from Google’s Polymer Project.',
    eventTitle: 'DevFest KC',
    tags: ['webcomponents', 'polymer'],
    location: 'Kansas City, MO',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1P4T2_aMgJlOO4seH4P6sDcQMgcAKkjUaOB-izjFVIdw',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://devfestkc.com/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZhHuFAWhgI4tlPmB',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Leverage the power of native with Progressive Web Apps',
    date: 'Februery 18th, 2017',
    description: 'As developers, we want to create apps that engage users across multiple devices. But building native apps is costly and cumbersome. Progressive Web Apps (PWAs) combine the power of native apps with the ease of building and deploying web apps. Learn to craft PWA experiences using new web standards, including service workers, push notifications, and homescreen access.',
    eventTitle: 'DevFest KC',
    tags: ['progressivewebapps'],
    location: 'Kansas City, MO',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1uONFEBmXg6k1LZvC4KPXMCyrEMhEeOG8_2_UQ1-uzio',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://devfestkc.com/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZed8RQb9Pz5LvMOY',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Get talking with Actions on Google',
    date: 'Februery 18th, 2017',
    description: 'Let your users be the voice talent with Actions on Google. Learn how to design, develop, and distribute rich conversational experiences or direct action commands. We’ll show you how to approach voice-driven, natural language interactions with API.AI’s powerful bot platform.',
    eventTitle: 'DevFest KC',
    tags: ['actionsongoogle'],
    location: 'Kansas City, MO',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1L_IDKj0GzFmadZM__XAGo-7AzGDvlsFRUsid80O5TM0',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://devfestkc.com/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZaHltvInXVa-kjNt',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Get talking with Actions on Google',
    date: 'Februery 8th, 2017',
    description: 'Let your users be the voice talent with Actions on Google. Learn how to design, develop, and distribute rich conversational experiences or direct action commands. We’ll show you how to approach voice-driven, natural language interactions with API.AI’s powerful bot platform.',
    eventTitle: 'GDG Chicago',
    tags: ['actionsongoogle'],
    location: 'Chicago, IL',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1EjoqN1gs7Pfr_RRHRNI7CmNJmL4DgxzEFsroAkbpU7A',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.meetup.com/Google-Developers-Group-GDG-Chicago/events/237220640/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZWvDU7VUnyPTDmSA',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Burn down your competitors with Firebase',
    date: 'December 5th, 2016',
    description: 'Google’s Firebase provides a suite of products to help you quickly build realtime apps. We’ll show how Firebase can take care of authentication, database, storage, and scaling while you concentrate on user experience and building an amazing product.',
    eventTitle: 'ConFoo Vancouver',
    tags: ['firebase'],
    location: 'Vancouver, BC, CA',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1UBKBBubWQtIniOGsu8jFKpFm0j2abRacGwRxyxMqBEc',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://confoo.ca/en/yvr2016',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZRBmB_NDgJ6z2m0T',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Energize your development flow with CLIs',
    date: 'December 7th, 2016',
    description: 'Creating personalized CLIs can help you streamline recurring tasks, such as setting up new development environments, managing deployments, and wrangling data. We will walk you through building CLIs in Ruby to help you avoid costly mistakes and ensure consistent results. Create simple commands that perform powerful tasks.',
    eventTitle: 'ConFoo Vancouver',
    tags: ['cli', 'ruby'],
    location: 'Vancouver, BC, CA',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1hB8NNTm8AwelCeARZO9wc_bL-3cabTbhDvccAWXGujM',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://confoo.ca/en/yvr2016',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZPN8eZVq6gUOfuQm',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego bricks of the web',
    date: 'November 3rd, 2016',
    description: 'Writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Ditch large, complex frameworks and drop these lightweight building blocks into your site. We will show you how to build, test, and deploy a web component, and introduce you to the wide selection of existing web components available through Google\'s Polymer.',
    eventTitle: 'DevFest West',
    tags: ['webcomponents', 'polymer'],
    location: 'Mountain View, CA',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1TG01U4MpZCPHsTzPdICVGMiIik_onEGJAeTIoAj47ds',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://devfest2016.gdgsv.com/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZMwl5K6WfArx9xkz',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Leverage the power of native with Progressive Web Apps',
    date: 'November 3rd, 2016',
    description: 'As developers, we want to create apps that engage users across multiple devices. But building native apps is costly and cumbersome. Progressive Web Apps (PWAs) combine the power of native apps with the ease of building and deploying web apps. Learn to craft PWA experiences using new web standards, including service workers, push notifications, and homescreen access.',
    eventTitle: 'Mobile Era',
    tags: ['progressivewebapps'],
    location: 'Oslo, Norway',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1uRDz3fStZ8oNBi3TK4K0fgIp0rlfsOz8jRhpaUCDGsA',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://mobileera.rocks/',
        tag: false,
        service: 'external',
      },
      {
        title: 'Video',
        url: 'https://vimeo.com/190713344',
        tag: true,
        service: 'vimeo',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZKom6cxpaOUtaxkK',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego bricks of the web',
    date: 'October 20th, 2016',
    description: 'Writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Ditch large, complex frameworks and drop these lightweight building blocks into your site. We will show you how to build, test, and deploy a web component, and introduce you to the wide selection of existing web components available through Google\'s Polymer.',
    eventTitle: 'Connect.Tech',
    tags: ['webcomponents', 'polymer'],
    location: 'Atlanta, GA',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/10mwL3h6RbjxEAH94M022EgHzFkIO_6lIb_HUWmT3l00',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'http://connect.tech/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZIrGfzwEjp7UKulY',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Web Components: Lego bricks of the web',
    date: 'October 1st, 2016',
    description: 'Writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Ditch large, complex frameworks and drop these lightweight building blocks into your site. We will show you how to build, test, and deploy a web component, and introduce you to the wide selection of existing web components available through Google\'s Polymer.',
    eventTitle: 'Madison PHP Conference',
    tags: ['webcomponents', 'polymer'],
    location: 'Madison, WI',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1TG01U4MpZCPHsTzPdICVGMiIik_onEGJAeTIoAj47ds',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'http://2016.madisonphpconference.com/',
        tag: false,
        service: 'external',
      },
      {
        title: 'Reviews',
        url: 'https://joind.in/event/madison-php-conference-2016/web-components-lego-bricks-of-the-web',
        tag: true,
        service: 'joindin',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZGc2sMFHbGMkaRNc',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'Leverage the power of native with Progressive Web Apps',
    date: 'September 16th, 2016',
    description: 'Writing the same login form over and over again? Web components offer a modular approach to creating reusable UI widgets. Ditch large, complex frameworks and drop these lightweight building blocks into your site. We will show you how to build, test, and deploy a web component, and introduce you to the wide selection of existing web components available through Google\'s Polymer.',
    eventTitle: 'Windy City DevCon',
    tags: ['progressivewebapps'],
    location: 'Chicago, IL',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1Cr_Cf2Ef9L7ojQWUTy0kuDMUZHqMYf3d_PO1MQkBtg4',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.meetup.com/Google-Developers-Group-GDG-Chicago/events/232947796/',
        tag: false,
        service: 'external',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  },
  {
    id: '-KrvZAS455BHznj4ugI2',
    speakers: ['-KsZTL-5U4v1UYxq4Zbp', '-KsZTNlw7dpLoH5mrsT4'],
    title: 'The Bendy Game of Life³',
    date: 'June 15th, 2016',
    description: 'The Bendy Game of Life is a 3D version of Conway’s Game of Life, which simulates the evolution of a population given initial settings chosen by the player. Visually, the game board is a 3D grid with a variable number of cells filled in or “alive.” Depending on the number of “alive” or “dead” neighbor cells each cell has, it will die, survive, or come alive in the next turn or “generation.” Generations continue following this algorithm until the population stabilizes.',
    eventTitle: 'Madhackers',
    tags: ['threejs', 'ruby', '⚡'],
    location: 'Madison, WI',
    links: [
      {
        title: 'Slides',
        url: 'https://docs.google.com/presentation/d/1idTXiseohF54-OTHLTReKgFGDxbOVlCAX9UMYUFiois',
        tag: false,
        service: 'google-slides',
      },
      {
        title: 'Event',
        url: 'https://www.meetup.com/madhackers/events/231725576/',
        tag: false,
        service: 'external',
      },
      {
        title: 'Video',
        url: 'https://www.youtube.com/watch?v=_hewWDDvkMQ',
        tag: true,
        service: 'youtube',
      },
    ],
    sponsors: ['-Kt8bVVFVc8xQNx9AP_E'],
  }
].map(deck => {
  deck.links = deck.links.map(link => new Link(link));
  return new Deck(deck);
});
