name: Deploy Preview
on: pull_request

jobs:
  deploy_preview:
    runs-on: ubuntu-22.04 # https://github.com/puppeteer/puppeteer/issues/12818
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - uses: firebaseextended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SLIDES_TODAY }}'
          projectId: slides-today
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
