name: Scanning
on:
  push:
  schedule:
    - cron: '0 15 * * 0'
jobs:
  CodeQL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: github/codeql-action/init@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: npm ci
    - run: npm run build:development
    - uses: github/codeql-action/analyze@v1
