name: Sync Firestore
on:
  push:
    branches:
      - main
    paths:
      - src/app/*.data.json
      - src/app/collections.ts
      - scripts/sync-firestore.ts
      - .github/workflows/sync-firestore.yaml
jobs:
  sync:
    runs-on: ubuntu-22.04 # https://github.com/puppeteer/puppeteer/issues/12818
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: npm install -g npm@11
      - run: npm ci
      - run: echo "$FIREBASE_SERVICE_ACCOUNT" > "$RUNNER_TEMP/service-account.json"
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - run: npm run sync-firestore
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/service-account.json
          GCLOUD_PROJECT: slides-today
